name: Docker Build - Push to DockerHub

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      RUBY_VERSION: ruby-2.7.1  # == $(cat .ruby-version | head -n 1)
      NODE_VERSION: 10.15.2     # == $(cat .nvmrc | head -n 1)
      USER_UID:     1000        # == $(id -u)
      USER_GID:     1000        # == $(id -g)

    steps:
      - uses: actions/checkout@v2
      - name: Building the image
        run: docker build --build-arg RUBY_VERSION=${RUBY_VERSION} --build-arg NODE_VERSION=${NODE_VERSION} --build-arg USER_UID=${USER_UID} --build-arg USER_GID=${USER_GID} -t docker.pkg.github.com/sagium/rails_base/rails_base:${RUBY_VERSION}_node-${NODE_VERSION} .

      - name: Push to DockerHub
        run: |
          echo '${{ secrets.GITHUB_TOKEN }}' | docker login docker.pkg.github.com -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push docker.pkg.github.com/sagium/rails_base/rails_base:${RUBY_VERSION}_node-${NODE_VERSION}
