name: Docker Build - Pull request checks

on: [ pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      USER_UID:     1000        # == $(id -u)
      USER_GID:     1000        # == $(id -g)

    steps:
      - uses: actions/checkout@v2
      - name: Building the image
        run: |
          export RUBY_VERSION=$(cat .ruby-version | head -n 1)
          export NODE_VERSION=$(cat .nvmrc | head -n 1)
          docker build --build-arg RUBY_VERSION=${RUBY_VERSION} --build-arg NODE_VERSION=${NODE_VERSION} --build-arg USER_UID=${USER_UID} --build-arg USER_GID=${USER_GID} -t docker.pkg.github.com/sagium/rails_base/rails_base:${RUBY_VERSION}_node-${NODE_VERSION} -t sagium2/rails_base:${RUBY_VERSION}_node-${NODE_VERSION} .

      - name: Check RUBY version
        run: |
          export RUBY_VERSION=$(cat .ruby-version | head -n 1)
          export NODE_VERSION=$(cat .nvmrc | head -n 1)
          RUBY_VERSION_FOR_GREP=$(echo $RUBY_VERSION | sed 's/-/ /g')
          HAS_RUBY=$(docker run --rm sagium2/rails_base:${RUBY_VERSION}_node-${NODE_VERSION} /bin/bash -l -c "ruby -v | grep '${RUBY_VERSION_FOR_GREP}'")
          if [ -n "${HAS_RUBY}" ]; then echo ${HAS_RUBY}; else exit 1; fi

      - name: Check NODE version
        run: |
          export RUBY_VERSION=$(cat .ruby-version | head -n 1)
          export NODE_VERSION=$(cat .nvmrc | head -n 1)
          NODE_VERSION_FOR_GREP="v$(echo $NODE_VERSION)"
          HAS_NODE=$(docker run --rm sagium2/rails_base:${RUBY_VERSION}_node-${NODE_VERSION} /bin/bash -l -c "node -v | grep '${NODE_VERSION_FOR_GREP}'")
          if [ -n "${HAS_NODE}" ]; then echo ${HAS_NODE}; else exit 1; fi
