name: Docker Build - Pull request checks

on: [ pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      USER_UID:     1000        # == $(id -u)
      USER_GID:     1000        # == $(id -g)

    steps:
      - uses: actions/checkout@v2
      - name: Building and testing the image
        run: /bin/bash .github/workflows/helpers/build_image.sh
