name: Docker Build - Push to DockerHub

on:
  push:
    branches:
      - 'ruby*node*'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      USER_UID:     1000        # == $(id -u)
      USER_GID:     1000        # == $(id -g)

    steps:
      - uses: actions/checkout@v2
      - name: Building and test the image
        run: /bin/bash .github/workflows/helpers/build_image.sh

      - name: Push to DockerHub
        run: |
          export RUBY_VERSION=$(cat .ruby-version | head -n 1)
          export NODE_VERSION=$(cat .nvmrc | head -n 1)
          echo '${{ secrets.DOCKER_PASSWORD }}' | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push sagium2/rails_base:${RUBY_VERSION}_node-${NODE_VERSION}

      - name: Push as Github package
        run: |
          export RUBY_VERSION=$(cat .ruby-version | head -n 1)
          export NODE_VERSION=$(cat .nvmrc | head -n 1)
          echo '${{ secrets.GITHUB_TOKEN }}' | docker login docker.pkg.github.com -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push docker.pkg.github.com/sagium/rails_base/rails_base:${RUBY_VERSION}_node-${NODE_VERSION}
